### ISSUE TITLE
You are in the blacklist !

### ISSUE THREAD

**Issue by AliMD** [AveVlad/gulp-connect#105]
Excuse me
Do you know you are in the gulpjs blacklist ?
http://gulpjs.com/plugins/blackList.json

The reason: `use the connect module directly`
How can you fix this issue and why theme block you ?!

**Comment by AveVlad** [comment]
@AliMD ![](http://301-1.ru/gen-mems/img_mems/018e8b760f5cda5a973cd09a11855455.jpg)

**Comment by david-gang** [comment]
@AliMD . Black list is a sort of opinion. The gulp core developers feel somehow that connect should be used directly. 
As you can see at https://www.npmjs.com/package/gulp-connect there are 50000 downloads in the last month. This is because gulp-connect makes using connect much more convenient.
https://github.com/gulpjs/plugins/issues/56#issuecomment-44616168

When you use connect a lot of times, you would end in writing a convenience function which would not be different than this module.

So i am not concerned about the opinionated option of the gulp core developers.

**Comment by AliMD** [comment]
@dnakov after i fully understande the gulp structure i think we must use connect directly and no need to use a seperate plugin
its a very good structure and i'm so happy to migrate from grunt to gulp
check these example for more information: https://github.com/gulpjs/gulp/tree/master/docs/recipes
by the way i'm also migrate from direct use of connect to browserSync, check the doc https://github.com/gulpjs/gulp/blob/master/docs/recipes/server-with-livereload-and-css-injection.md

**Comment by AliMD** [comment]
@dnakov after i fully understande the gulp structure i think we must use connect directly and no need to use a seperate plugin
its a very good structure and i'm so happy to migrate from grunt to gulp
check these example for more information: https://github.com/gulpjs/gulp/tree/master/docs/recipes
by the way i'm also migrate from direct use of connect to browserSync, check the doc https://github.com/gulpjs/gulp/blob/master/docs/recipes/server-with-livereload-and-css-injection.md

**Comment by AveVlad** [comment]
@AliMD L@L

**Comment by AliMD** [comment]
@avevald please guide me if I wrong
