### ISSUE TITLE
LiveReload is broken

### ISSUE THREAD

**Issue by bkrrrr** [avevlad/gulp-connect#252]
connect.reload(); isn`t working, i debugged it till the [map-stream](https://www.npmjs.com/package/map-stream). But i could really figure out how this works.

Below is also a workaround

package.json:

```json
"devDependencies": {
    "del": "^3.0.0",
    "gulp": "^4.0.0",
    "gulp-beautify": "^2.0.1",
    "gulp-connect": "^5.5.0",
    "gulp-eslint": "^4.0.2",
    "http-proxy-middleware": "^0.17.4",
  },
```

gulp.js
```javascript
const gulp = require('gulp');
const ui5preload = require('gulp-ui5-preload');
const connect = require('gulp-connect');
let connectApp;

gulp.task('connect', function (done) {
    connectApp = connect.server(
        {
            root: ['webapp', 'libs'],
            livereload: true,
            port: 8000
        }
    );
});

gulp.task('watch', function () {
    gulp.watch(configBuild.gulp.webapp + '/**/*').on('change',  function(event){
        debugger;
        // workaround works somehow
        let filename = event.substr(0,configBuild.gulp.webapp.length + 1 );
        connectApp.lr.changed(  {body: {
            files: [filename]}});
        

        // doesn't WORK
        // connect.reload();
    });
});

gulp.task('default', gulp.parallel('connect','watch'));
```

**Comment by toptalo** [comment]
Same issue

**Comment by Dawnut** [comment]
Same here, tried multiple versions back to 2.0.6  - no luck. using NodeJs 9x, Gulp 4, babel, everything else works, connect.reload() simply doesn't

**Comment by jershell** [comment]
ubuntu 18.04
npm 5.6.0
node v8.11.3
```
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-connect": "^5.5.0"
  }
```
livereload is not working
I use config from documentation

**Comment by sergeymorkovkin** [comment]
Same here. It appears it doesn't work with Webpack 4.

**Comment by sergeymorkovkin** [comment]
Anyway, my solution was this:

`const { gulp, src, dest, watch, series, parallel } = require('gulp');
const connect = require('gulp-connect');

function taskServe() {
  connect.server({
    root: 'app',
    livereload: true,
  });
  return Promise.resolve(null);
};

function taskWatch() {
  watch('app/*.html', taskHtml);
};

function taskHtml() {
  src('./app/*.html')
    .pipe(dest('./app'))
    .pipe(connect.reload());
};

exports.serve = taskServe;
exports.html = taskHtml;
exports.watch = taskWatch;
exports.default = series(taskServe, taskWatch);`

1. Use Gulp 4 approach to task definition.
2. Make sure taskServe resolves.
3. Use series() to combine taskServe() and taskWatch().

**Comment by toptalo** [comment]
```
$ gulp --version
CLI version 2.0.1
Local version 3.9.1
```

**Comment by mojavelinux** [comment]
`connect.reload()` expects to be called at the end of a file stream. It takes the file it receives and passes `file.path` to the livereload server so it does it's thing.

Here's the simplest way I can demonstrate it working with Gulp 4.

```js
const { parallel, src, watch } = require('gulp')
const connect = require('gulp-connect')

function serveTask (done) {
  connect.server({    
    root: 'public',
    livereload: true,
    port: 8000,
  }, function () { this.server.on('close', done) })
} 

function watchTask (done) {
  watch('public').on('change', (filepath) =>
    src(filepath, { read: false }).pipe(connect.reload()))
  done()
} 

module.exports.default = parallel(serveTask, watchTask)
```

If you change the local file `public/index.html`, you should see that the page loaded at `http://localhost:8000/index.html` is reloaded.

It's not possible to use the event directly from the watch function since it doesn't send any file information (unless the receiving task itself generates a file stream that you can pipe to `connect.reload()`). That's why we use `on('change')`. You can use other events as well.

Just remember that `connect.reload()` produces a stream map that expects to pick off files from a stream. It's not a void function.

NOTE: It's necessary to pass done to the server close event to allow Ctrl+C to terminate cleanly.

gulp-connect: 5.7.0
gulp: 4.0.0

**Comment by johnybrownalreadytaken** [comment]
@mojavelinux
would you by any chance know how to modify code from this course,
I've tried on my own after reading your replay but couldn't do it

my issue: [upgrade connect livereload to gulp 4](https://github.com/planetoftheweb/workflows/issues/9)
original source: [](https://github.com/planetoftheweb/workflows/blob/master/gulpfile.js)

**Comment by mojavelinux** [comment]
I've shared the advice I have time to share.

**Comment by johnybrownalreadytaken** [comment]
this worked for me

```
gulp.task('css', function() {
  return gulp.src(PATH)
    // ..
    .pipe(connect.reload());
})

gulp.task('connect', function(done) {
  connect.server({
    root: 'builds/development/',
    livereload: true
  })
  done()
});

gulp.task('watch', function(done) {
// ..
  gulp.watch(PATH, gulp.series('css'));
  done()
})

gulp.task('default', gulp.parallel('connect', 'watch'));
```

**Comment by mojavelinux** [comment]
Note that if you want to monitor generated files instead of the source files, you need to use gulp.src at the end of your build step to pass the generated files to reload (so a different stream).

In other words, something like:

```js
function build (done) {
  generateFilesAsync()
    .then(() => {
      // **/*.ext is a glob of generated files
      src('**/*.ext', { read: false })
        .on('finish', done)
        .pipe(connect.reload())
    })
}
```

Of course, you could just pass a fixed set of files to reload and let the browser sort out what's interesting.

**Comment by imdragonet** [comment]
according to gulp documentation
`https://gulpjs.com/docs/en/getting-started/async-completion`
a task should return a stream, promise, event emitter, child process, or observable, so that gulp knows whether to continue or end.

while  **connect.server**  returns ConnectAppOptions object, 
```typescript
export function server(options?: ConnectAppOptions): ConnectAppOptions
```
so if we put watch tasks after connect, gulp stops at connect task, watch task will not be executed by gulp.

@johnybrownalreadytaken do it right, call the callback function after connect.server
