### ISSUE TITLE
Multiple hosts

### ISSUE THREAD

**Issue by dgateles** [avevlad/gulp-connect#264]
How to setup with a multiple hosts option?
I need to expose the webserver on localhost and on my IPV4

**Comment by carlososuna86** [comment]
I was having problems connecting to the webserver, both from the internet and from the virtual machine running the webserver (inside Docker).

After days trying different solutions, I found that if you pass a list instead of a single value, `gulp-connect` will allow connections from anywhere. I tried passing multiple host names, just localhost, or even an empty list []. 

https://github.com/carlososuna86/hello-gulp/blob/aa7d3e0b189a8610147e335320c6d0c98674e448/app/html/gulpfile.js#L33

**Comment by dgateles** [comment]
Thank you man! Worked!
